lib/path: cleanup path functions
util-linux/util-linux pull request #2535
Opened 2023-10-08 19:09 UTC by stoeckmann

- Avoid an out of boundary access on illegal /sys files
- Better error handling
- Remove ul_prefix_fopen
- Fix typos

2023-10-08 21:05 UTC, t-8ch requested changes

2023-10-08 21:05 UTC, t-8ch commented on sys-utils/lscpu-virt.c
> +			fd = ul_path_fopen(cxt->rootfs, "r", _PATH_SYS_HYP_FEATURES);
And how has this ever worked?
The `mode` and `path` arguments are passed in the wrong order...

2023-10-09 06:52 UTC, stoeckmann commented on lib/path.c
> +			errno = EINVAL;
The `errno` variable is set by `malloc` which is called within `cpuset_alloc` so I would keep it the way it is. The system library will know best why the allocation failed.

2023-10-09 06:53 UTC, stoeckmann commented on sys-utils/lscpu-virt.c
> +			fd = ul_path_fopen(cxt->rootfs, "r", _PATH_SYS_HYP_FEATURES);
Oh, nice catch. :D

2023-10-09 06:59 UTC, t-8ch commented on lib/path.c
> +			errno = EINVAL;
For `malloc` indeed. `fgets` on the other hand does not.
See the discussion in #1821.

2023-10-09 07:17 UTC, t-8ch commented on lib/path.c
> +			errno = EINVAL;
If errors are communicated in two different ways, at least those should give consistent values.
So on `malloc` failure the function should return `-errno`.

Or we rework it to only use one error mechanism, there aren't many users of this function.

2023-10-09 10:43 UTC, karelzak commented on lib/path.c
> +			errno = EINVAL;
Please, keep it return <0 as error, it's almost everywhere as standard in the code.

2023-10-10 19:10 UTC, stoeckmann commented on sys-utils/lscpu-virt.c
> +			fd = ul_path_fopen(cxt->rootfs, "r", _PATH_SYS_HYP_FEATURES);
We cannot replace all fscanf calls due to a while-loop, but I have adjusted the other ones.

2023-10-10 19:10 UTC, stoeckmann commented on lib/path.c
> +			errno = EINVAL;
I have added an explicit errno assignment in case of fgets failure

2023-10-10 19:12 UTC, t-8ch approved these changes
Thanks!

2023-10-23 10:51 UTC, merged