sfdisk: add --discard-free
util-linux/util-linux pull request #3198
Opened 2024-09-16 13:09 UTC by karelzak

Why do we need this? It can be difficult for end-users to discard
    unpartitioned areas using blkdiscard, as it requires using fdisk to
    obtain a list of free areas and then using blkdiscard with the correct
    --offset and --length options. It is less risky for end-users to use
    (s)fdisk, as they have a better understanding of the disk layout.

2024-09-16 18:11 UTC, t-8ch requested changes

2024-09-16 18:11 UTC, t-8ch commented on disk-utils/sfdisk.c
> +			rc = -errno;
`fdisk_warn()` could have overwritten `errno` already.

2024-09-16 18:11 UTC, t-8ch commented on disk-utils/sfdisk.c
> +		{ "discard-free", no_argument, NULL, OPT_DISCARDFREE },
bash completion is missing

2024-09-17 11:21 UTC, karelzak commented
@t-8ch thanks!

2024-09-17 11:25 UTC, t-8ch approved these changes

2024-09-18 08:31 UTC, merged