Skip tmpfs-sensitive tests if fstype cannot be determined
util-linux/util-linux pull request #3282
Opened 2024-11-13 14:17 UTC by zeha

In certain isolation environments (f.e. Debian's sbuild+unshare), `/proc/mounts` does not have an entry for the directory we're building in.

Then, findmnt as used in the tests returns nothing. As the build directory might very well be on tmpfs (and often is, in Debian), disable the two tests known to fail on tmpfs.

Relatedly, this was noticed because torvalds/linux@e88e0d366f9cfbb810b0c8509dc5d130d5a53e02 changed the behaviour of the underlying syscalls on tmpfs in Linux 6.6.

Closes: #3266

Debian bug #1086706

2024-11-14 05:12 UTC, t-8ch requested changes

2024-11-14 05:12 UTC, t-8ch commented on tests/ts/fincore/count
> +if [[ "$FILE_FS" = "tmpfs" || "$FILE_FS" = "overlay" || "$FILE_FS" = "" ]]; then
It should be `$FS` instead of `$FILE_FS` here.
(Or even better, they should be aligned)

2024-11-15 11:25 UTC, zeha commented
salsa.debian.org CI is still unhappy about fadvise/drop, but maybe this is a different problem. https://salsa.debian.org/debian/util-linux/-/jobs/6597060
From what I can tell, in salsa CI, the filesystem is probably ext4, maybe with overlay involved. 🤷🏼

2024-11-16 06:09 UTC, t-8ch approved these changes

2024-11-18 10:11 UTC, merged